version: "3"

networks:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - backend

  mysql:
    image: mariadb
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql

    networks:
      - backend

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRAY: 1
    restart: always
    ports:
      - "8081:80"

    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8.1_chapar
    volumes:
      - ./src/:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - backend

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --replica-read-only no --requirepass chapar#123@321*
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - backend

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - backend

